### ISSUE TITLE
Create web UI

### ISSUE THREAD

**Issue by fadookie** [fadookie/masto-list-importer#1]
Create a web UI for this tool to make it easier to use. Possibly host on GitHub Pages or Codesandbox.

Please react with a 👍 to this issue if you want this, or ping me at [@Eliot_L@social.coop](https://social.coop/@Eliot_L). I don't know if I will want to expend the effort to do this unless there's demand.

**Comment by kerim** [comment]
Please! The instructions are a bit complicated for me. I could probably do it, but it would take a weekend I feel...

**Comment by fadookie** [comment]
Thanks for letting me know. There are enough interested parties I have begun work on a bare bones web UI. You will still need to generate an API key but this will make it so you can complete the whole process from your browser.

**Comment by fadookie** [comment]
Web UI is now available at https://www.eliotlash.com/masto-list-importer/
